[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ghosttrap-sdk"
version = "0.4.11"
description = "Drop-in error reporter for ghosttrap.io"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = []

[project.urls]
Homepage = "https://github.com/alex-rowley/ghosttrap-sdk"

[tool.setuptools.packages.find]
include = ["ghosttrap*"]

[tool.setuptools.package-data]
"ghosttrap.django" = ["static/ghosttrap/*.js"]
